name: Testes com docker

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Subir containers com docker compose
              run: docker compose up -d backend frontend


            - name: Aguardar os serviços subirem
              run: sleep 10

            - name: Rodar testes do cypress
              run: docker compose run --rm cypress

            - name: Salvar evidencias
              if: always()
              uses: actions/upload-artifact@v4
              with: 
                name: evidencias-cypress
                path:  
                    cypress/videos/
                    cypress/screenshots/

            - name: Derrubar containers
              if: always()
              run: docker compose down